"""empty message

Revision ID: 1a1764d4ba4a
Revises: 
Create Date: 2025-12-17 14:43:28.143167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1764d4ba4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('email_primary', sa.String(length=255), nullable=False),
    sa.Column('email_support', sa.String(length=255), nullable=True),
    sa.Column('hours_of_operation', sa.JSON(), nullable=False),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('google_maps_embed_url', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'REPLIED', name='contactmessagestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('PHOTOGRAPHY', 'VIDEOGRAPHY', name='servicecategory'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_min', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_max', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_display', sa.String(length=100), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PHOTOGRAPHER', 'STAFF', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=False),
    sa.Column('preferred_time', sa.Time(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohorts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('current_enrollment', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='cohortstatus'), nullable=False),
    sa.Column('course_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('registration_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('schedule_details', sa.Text(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('WEDDINGS', 'PORTRAITS', 'EVENTS', 'COMMERCIAL', name='portfoliocategory'), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('shoot_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('selected_services', sa.JSON(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_location', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('referral_source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACCEPTED', 'REJECTED', name='quotestatus'), nullable=False),
    sa.Column('quoted_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('quote_details', sa.Text(), nullable=True),
    sa.Column('quote_sent_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'PENDING', name='emaillogstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('related_booking_id', sa.Integer(), nullable=True),
    sa.Column('related_quote_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['related_quote_id'], ['quote_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('education_occupation', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('has_own_camera', sa.Boolean(), nullable=False),
    sa.Column('learning_goals', sa.Text(), nullable=True),
    sa.Column('preferred_intake', sa.String(length=50), nullable=True),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INTERVIEW_SCHEDULED', 'ACCEPTED', 'REJECTED', 'ENROLLED', 'COMPLETED', name='enrollmentstatus'), nullable=False),
    sa.Column('registration_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('email_logs')
    op.drop_table('quote_requests')
    op.drop_table('portfolio_items')
    op.drop_table('cohorts')
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('contact_messages')
    op.drop_table('business_info')
    # ### end Alembic commands ###
